//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliJob.Company {
    public partial class ViewCandidateReport {
        protected global::System.Web.UI.WebControls.Literal litCandidateName;
        protected global::System.Web.UI.WebControls.Literal litCandidateEmail;
        protected global::System.Web.UI.WebControls.Literal litRole;
        protected global::System.Web.UI.WebControls.Literal litLevel;
        protected global::System.Web.UI.WebControls.Literal litType;
        protected global::System.Web.UI.WebControls.Literal litTechStack;
        protected global::System.Web.UI.WebControls.Literal litDate;
        protected global::System.Web.UI.WebControls.Literal litTotalScore;
        protected global::System.Web.UI.WebControls.Literal litFinalAssessment;
        protected global::System.Web.UI.WebControls.Literal litScoreCards;
        protected global::System.Web.UI.WebControls.Literal litStrengths;
        protected global::System.Web.UI.WebControls.Literal litAreas;
    }
}
