//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliJob.User
{
    public partial class ApplicationResumeBuild
    {
        protected global::System.Web.UI.WebControls.Label lblMsg;

        protected global::System.Web.UI.WebControls.Label lblJobInfo;

        protected global::System.Web.UI.WebControls.Label lblDraftNote;

        protected global::System.Web.UI.WebControls.TextBox txtAppResumeHeadline;

        protected global::System.Web.UI.WebControls.TextBox txtAppResumeSummary;

        protected global::System.Web.UI.WebControls.TextBox txtAppResumeSkills;

        protected global::System.Web.UI.WebControls.TextBox txtAppResumeEducation;

        protected global::System.Web.UI.WebControls.TextBox txtAppResumeExperienceDetails;

        protected global::System.Web.UI.WebControls.TextBox txtAppResumeProjects;

        protected global::System.Web.UI.WebControls.TextBox txtAppResumeCertifications;

        protected global::System.Web.UI.WebControls.TextBox txtAppResumeLanguages;

        protected global::System.Web.UI.WebControls.HyperLink lnkBackToJob;

        protected global::System.Web.UI.WebControls.Button btnConfirm;
    }
}
