//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliJob.User
{
    public partial class InterviewHistory
    {
        protected global::System.Web.UI.WebControls.Literal litTotalInterviews;
        protected global::System.Web.UI.WebControls.Literal litCompletedCount;
        protected global::System.Web.UI.WebControls.Literal litAvgScore;
        protected global::System.Web.UI.WebControls.Literal litBestScore;
        protected global::System.Web.UI.WebControls.Repeater rptInterviews;
        protected global::System.Web.UI.WebControls.Literal litEmpty;
    }
}
