//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliJob.User
{
    public partial class InterviewFeedback
    {
        protected global::System.Web.UI.WebControls.Literal litRole;
        protected global::System.Web.UI.WebControls.Literal litTotalScore;
        protected global::System.Web.UI.WebControls.Literal litDate;
        protected global::System.Web.UI.WebControls.Literal litLevel;
        protected global::System.Web.UI.WebControls.Literal litType;
        protected global::System.Web.UI.WebControls.Literal litFinalAssessment;
        protected global::System.Web.UI.WebControls.Literal litScoreCards;
        protected global::System.Web.UI.WebControls.Literal litStrengths;
        protected global::System.Web.UI.WebControls.Literal litAreas;
        protected global::System.Web.UI.WebControls.Panel pnlRetake;
        protected global::System.Web.UI.WebControls.Button btnReEvaluate;
        protected global::System.Web.UI.WebControls.HiddenField hdnInterviewId;
        protected global::System.Web.UI.WebControls.Panel pnlRegenerate;
        protected global::System.Web.UI.WebControls.Button btnRegenerate;
    }
}
