//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliJob.User {
    public partial class InterviewAccess {
        protected global::System.Web.UI.WebControls.HiddenField hdnJobId;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.Button btnEnter;
    }
}
