//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliJob.User {
    
    
    public partial class ResumeEnhancer {
        
        /// <summary>
        /// litRole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litRole;
        
        /// <summary>
        /// litCompany control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCompany;
        
        /// <summary>
        /// litLevel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLevel;
        
        /// <summary>
        /// litInterviewType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litInterviewType;
        
        /// <summary>
        /// litResumeSource control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litResumeSource;
        
        /// <summary>
        /// litStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStatus;
        
        /// <summary>
        /// hfLoadedAppliedJobId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfLoadedAppliedJobId;
        
        /// <summary>
        /// hfLoadedInterviewId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfLoadedInterviewId;
        
        /// <summary>
        /// hfLoadedResumePath control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfLoadedResumePath;
        
        /// <summary>
        /// hfLoadedResumeSource control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfLoadedResumeSource;
        
        /// <summary>
        /// hfLoadedOriginalFileName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfLoadedOriginalFileName;
        
        /// <summary>
        /// hfResumePreviewJson control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfResumePreviewJson;
        
        /// <summary>
        /// hfEduCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfEduCount;
        
        /// <summary>
        /// hfExpCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfExpCount;
        
        /// <summary>
        /// hfProjCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfProjCount;
        
        /// <summary>
        /// phEduAddBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phEduAddBtn;
        
        /// <summary>
        /// phEduCards control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phEduCards;
        
        /// <summary>
        /// phExpAddBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phExpAddBtn;
        
        /// <summary>
        /// phExpCards control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phExpCards;
        
        /// <summary>
        /// phProjAddBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phProjAddBtn;
        
        /// <summary>
        /// phProjCards control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phProjCards;
        
        /// <summary>
        /// btnToggleEnhPreviewEdit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnToggleEnhPreviewEdit;
        
        /// <summary>
        /// txtEnhFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnhFullName;
        
        /// <summary>
        /// txtEnhEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnhEmail;
        
        /// <summary>
        /// txtEnhMobile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnhMobile;
        
        /// <summary>
        /// txtEnhCountry control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnhCountry;
        
        /// <summary>
        /// txtEnhAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnhAddress;
        
        /// <summary>
        /// txtEnhLinkedIn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnhLinkedIn;
        
        /// <summary>
        /// txtEnhPortfolio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnhPortfolio;
        
        /// <summary>
        /// txtEnhSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnhSummary;
        
        /// <summary>
        /// txtEnhSkillProgrammingLanguages control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnhSkillProgrammingLanguages;
        
        /// <summary>
        /// txtEnhSkillFrameworksLibraries control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnhSkillFrameworksLibraries;
        
        /// <summary>
        /// txtEnhSkillToolsCloudDatabases control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnhSkillToolsCloudDatabases;
        
        /// <summary>
        /// txtEnhSkillSoftSkills control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnhSkillSoftSkills;
        
        /// <summary>
        /// txtEnhSkillCustomHeading control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnhSkillCustomHeading;
        
        /// <summary>
        /// txtEnhSkillCustomItems control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnhSkillCustomItems;
        
        /// <summary>
        /// txtEnhResumeCertifications control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnhResumeCertifications;
        
        /// <summary>
        /// txtEnhResumeLanguages control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnhResumeLanguages;
        
        /// <summary>
        /// pnlEnhSaveOptions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEnhSaveOptions;
        
        /// <summary>
        /// btnCancelEnhancedResume control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelEnhancedResume;
        
        /// <summary>
        /// btnSaveEnhancedResume control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveEnhancedResume;
        
        /// <summary>
        /// litOverallVisual control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litOverallVisual;
        
        /// <summary>
        /// litAtsVisual control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAtsVisual;
        
        /// <summary>
        /// litSemanticVisual control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSemanticVisual;
        
        /// <summary>
        /// litKeywordVisual control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litKeywordVisual;
        
        /// <summary>
        /// litResumeSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litResumeSummary;
        
        /// <summary>
        /// litStrengths control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStrengths;
        
        /// <summary>
        /// litGaps control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litGaps;
        
        /// <summary>
        /// litRewriteSuggestions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRewriteSuggestions;
        
        /// <summary>
        /// litPriorityKeywords control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPriorityKeywords;
        
        /// <summary>
        /// litFinalAssessment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFinalAssessment;
        
        /// <summary>
        /// litHtmlPreviewFrame control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHtmlPreviewFrame;
        
        /// <summary>
        /// Button1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button1;
    }
}
