//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliJob.User
{


    public partial class ResumeEnhancer
    {

        /// <summary>
        /// litRole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litRole;

        /// <summary>
        /// litCompany control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litCompany;

        /// <summary>
        /// litLevel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litLevel;

        /// <summary>
        /// litInterviewType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litInterviewType;

        /// <summary>
        /// litStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litStatus;

        protected global::System.Web.UI.WebControls.HiddenField hfLoadedAppliedJobId;

        protected global::System.Web.UI.WebControls.HiddenField hfLoadedInterviewId;

        protected global::System.Web.UI.WebControls.HiddenField hfLoadedResumePath;

        protected global::System.Web.UI.WebControls.HiddenField hfLoadedResumeSource;

        protected global::System.Web.UI.WebControls.HiddenField hfLoadedOriginalFileName;

        /// <summary>
        /// litOverallScore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litOverallScore;

        /// <summary>
        /// litAtsScore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litAtsScore;

        /// <summary>
        /// litSemanticScore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litSemanticScore;

        /// <summary>
        /// litKeywordScore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litKeywordScore;

        /// <summary>
        /// litResumeSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litResumeSummary;

        /// <summary>
        /// litStrengths control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litStrengths;

        /// <summary>
        /// litGaps control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litGaps;

        /// <summary>
        /// litResumePreview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litResumePreview;

        protected global::System.Web.UI.WebControls.TextBox txtEnhFullName;

        protected global::System.Web.UI.WebControls.TextBox txtEnhEmail;

        protected global::System.Web.UI.WebControls.TextBox txtEnhMobile;

        protected global::System.Web.UI.WebControls.TextBox txtEnhAddress;

        protected global::System.Web.UI.WebControls.TextBox txtEnhHeadline;

        protected global::System.Web.UI.WebControls.TextBox txtEnhSummary;

        protected global::System.Web.UI.WebControls.TextBox txtEnhSkills;

        protected global::System.Web.UI.WebControls.TextBox txtEnhEducation;

        protected global::System.Web.UI.WebControls.TextBox txtEnhExperience;

        protected global::System.Web.UI.WebControls.TextBox txtEnhProjects;

        protected global::System.Web.UI.WebControls.TextBox txtEnhCertifications;

        protected global::System.Web.UI.WebControls.TextBox txtEnhLanguages;

        protected global::System.Web.UI.WebControls.Button btnToggleEnhPreviewEdit;

        protected global::System.Web.UI.WebControls.Panel pnlEnhSaveOptions;

        protected global::System.Web.UI.WebControls.RadioButtonList rblEnhSaveTarget;

        protected global::System.Web.UI.WebControls.Button btnSaveEnhancedResume;

        /// <summary>
        /// litRewriteSuggestions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litRewriteSuggestions;

        /// <summary>
        /// litPriorityKeywords control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litPriorityKeywords;

        /// <summary>
        /// litFinalAssessment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litFinalAssessment;
    }
}
