//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliJob.User
{
    public partial class TakeInterview
    {
        protected global::System.Web.UI.WebControls.Literal litRole;
        protected global::System.Web.UI.WebControls.Literal litLevel;
        protected global::System.Web.UI.WebControls.Literal litType;
        protected global::System.Web.UI.WebControls.Literal litTechStack;
        protected global::System.Web.UI.WebControls.Literal litUserAvatar;
        protected global::System.Web.UI.WebControls.Literal litUserName;
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;
        protected global::System.Web.UI.WebControls.HiddenField hdnInterviewId;
        protected global::System.Web.UI.WebControls.HiddenField hdnAnswersJson;
        protected global::System.Web.UI.WebControls.HiddenField hdnQuestionsJson;
        protected global::System.Web.UI.WebControls.Button btnSubmitAnswers;
    }
}
